### ISSUE TITLE
Infestor import path is not working correctly

### ISSUE THREAD

**Issue by Yhtiyar** [bugout-dev/infestor#10]
For now non relative path is only works if `reporter` is added in top level of repository.

**Comment by zomglings** [comment]
Relative paths are also not working:
1. Too many `.`s
2. For relative imports, the package name is being added after `.`s

**Comment by zomglings** [comment]
This can be fixed by correcting the behaviour of [`get_reporter_module_path`](https://github.com/bugout-dev/infestor/blob/python/v0.0.5/python/infestor/manager.py#L22).

We will rename this method to something like `get_reporter_config`.
